### ISSUE TITLE
  Some of your tests did a full page reload!

### ISSUE THREAD

**Issue by maruthi1255** [karma-runner/karma-jasmine#135]
While running karma test, getting the following error.
Do any one has any fix for this issue.

PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Some of your tests did a full page reload!

**Comment by akman003** [comment]
I also sometimes get this in PhantomJS 2.1.1. The quick fix is to restart karma, but I'm hoping the `--debug` flag will help determine if this is an issue with one of my tests or with PhantomJS/Karma.

**Comment by pe8ter** [comment]
Do you have multiple browsers in your Karma config?

I was seeing this error pretty much every time I ran my tests. I emptied the list of browsers in the Karma config and passed in a single browser at a time and I've never seen the error since. Had to change my test orchestration (Gulp) to account for this, but it was totally worth it.

**Comment by maksimr** [comment]
duplicate https://github.com/karma-runner/karma/issues/1101
